### ISSUE TITLE
报错了是因为什么原因呢？

### ISSUE THREAD

**Issue by flipped-cj** [RoadIsLong/52pojie_Sign#9]
应该是没找到 messagetext 这个 dom，find报错了

```
Traceback (most recent call last):
  File "/home/runner/work/52pojie_Sign/52pojie_Sign/main.py", line 40, in <module>
    main()
  File "/home/runner/work/52pojie_Sign/52pojie_Sign/main.py", line 35, in main
    sign_msg = sign(cookie=cookie)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/52pojie_Sign/52pojie_Sign/main.py", line 21, in sign
    fc = fb.find("div", id="messagetext").find("p").text
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find'
Error: Process completed with exit code 1.
```

**Comment by Dirket** [comment]
cookie变化了，应该是52网站改动了

**Comment by kangkang623** [comment]
> 

我更新了cookie也不行，应该是网站变更

**Comment by Dirket** [comment]
cookie变成动态的了，每次都不一样

**Comment by RoadIsLong** [comment]
本来想看下这个问题的,没成想运行脚本给我签到成功了...各位也可以再试试看看是不是又好了

**Comment by RoadIsLong** [comment]
> 

初步怀疑是开启了JS反爬

**Comment by Dirket** [comment]
确实好了

**Comment by UoToGK** [comment]
> 本来想看下这个问题的,没成想运行脚本给我签到成功了...各位也可以再试试看看是不是又好了

还是不行吧,显示需要登录的,更换cookie依然如此

**Comment by Dirket** [comment]
> > 本来想看下面这个问题的，没有想运脚本给我签到成功了...各位置也可以再试看看是不是又好了
> 
> 还是不行吧，表明需要登录的，更换cookie依然如此


粘贴cookie的时候看清楚，有些%号复制到github就没了

**Comment by longwangjiang** [comment]
确实还是不行。。。

**Comment by PeichenXie2012** [comment]
我的也是
